FROM postgres:12

RUN apt-get update && \
    apt-get install -y pgbackrest openssh-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    sed -i 's/#   StrictHostKeyChecking ask/   StrictHostKeyChecking no/' /etc/ssh/ssh_config

ENTRYPOINT ["tail", "-f", "/dev/null"]
